name: Deploy API 

on:
  push: 
    branches: 
      - develop
    paths: ['apps/api/**']
  workflow_dispatch:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate API

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install packages
        run: pnpm i

      - name: Check Formatting
        run: pnpm run format:check:api

      - name: Run Lint
        run: pnpm run lint:api

  deploy:
    needs: validate
    runs-on: macos-latest
    environment: stage
    name: Deploy API

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run deploy script
        run: |
          chmod +x ./scripts/deploy-api.sh
          ./scripts/deploy-api.sh ./infra/envs/dev

  







